### ISSUE TITLE
Doesn't actually save location

### ISSUE THREAD

**Issue by sydneybrokeit** [128keaton/barcodeWebChrome#2]
I attempted to change the extension to work using the deployable version, and when I change the IP, even to the existing server, the extension no longer functions.  No more printer lists, and attempting to open the dialog up again comes up as blank.

Tested on mine and K's laptops today.

**Comment by sydneybrokeit** [comment]
As a note, when I open the options dialog in expect, there is no listener for click

**Comment by ghost** [comment]
Did some digging, it does save the value, but the javascript seems to be unable to load the address from localStorage.

**Comment by 128keaton** [comment]
@hmschreck I saw that bug before leaving but decided not to say anything. If you address is set right, you should be fine. Make sure both printers.php and printers.txt are in the same directory on the server

**Comment by ghost** [comment]
It actually stops working should you attempt to set any other IP.  I have it like half-fixed now.

**Comment by ghost** [comment]
I think I got it, I'll put my fork and test it Monday.

**Comment by 128keaton** [comment]
@hmschreck really? I had it working fine actually changing IPs. Your form needs to be WITHOUT the 'http://'

**Comment by ghost** [comment]
Yeah, it wasn't even showing anything at all on mine or K's computer. When did you add the "load" listener?  That was the crux of the problem eventually (though I think I got it cleaned up slightly, as well).

**Comment by ghost** [comment]
I don't doubt it was working for you, though, I ran into some completely idiotic stuff while I was working on this.

edit: idiotic stuff in the way Chrome handles things.

**Comment by ghost** [comment]
I'll test this Monday, and if it works I'll create a pull request.

**Comment by 128keaton** [comment]
@hmschreck I went ahead and fixed it here, I didn't even look at your fork. I did some minor refactoring and made the printer list fetching Async so it wouldn't not display the popover (now it will show an error icon on printer list). I cannot fully test it, but I think it should work. You can put http:// in the field now, it will be automatically removed. Oh, and was it idiotic because of me? Or because of the cough drops?

**Comment by ghost** [comment]
No, it was idiotic because Chrome handles things weird :D

**Comment by ghost** [comment]
Cursory testing is showing the saving issue is resolved :)

**Comment by 128keaton** [comment]
@hmschreck perfecto
